### ISSUE TITLE
Complexit Crash when cluster=10 on sample file

### ISSUE THREAD

**Issue by carldister** [Cschimpf/Complex-It#6]
I was testing out clustering on a sample file from a network tutorial.  When I set cluster=10 in kmeans, it crashed - not sure why.   Here is the data:

[dsmexample2less1.zip](https://github.com/Cschimpf/Complex-It/files/1395080/dsmexample2less1.zip)

**Comment by Cschimpf** [comment]
I suspect what is happening and what happened on my end is that it
basically cannot find any solution because the data space (values are only
0 and 1) is sparse, the number of cases is low, and the number of
dimensions is somewhat high vis-a-vis the number of cases. The short
version is it basically couldn't find a unique solution for data of this
type and the number of clusters you specified. Kmeans isn't really good for
this kind of data, it can deal with different distributions with some
efficacy but generally it does well with data that is spherical in nature.
You can of course data with more than 3 variables on it, but its good at
finding clusters when data is distinguished in a spherical (spreads out
over x,y, z, ...etc) manner. This almost looks like an identity matrix, its
not quite that, but similar.

If you run it again and go back to the RStudio console after it errors and
copy the stack of errors for me. Mine looks like this:

Warning: Error in kmeans: more cluster centers than distinct data points.
Stack trace (innermost first):
    70: kmeans
    69: initialize [C:\Users\Corey Schimpf\Documents\SACS for R\new
interface Complexit/server.R#81]
    68: initialize
    67: new
    66: create_user_gen_kmeans_solution [C:\Users\Corey
Schimpf\Documents\SACS for R\new interface Complexit/global.R#28]
    65: observeEventHandler [C:\Users\Corey Schimpf\Documents\SACS for
R\new interface Complexit/server.R#81]
     1: shiny::runApp

I've seen this error before and ultimately I need to catch when it happens
and prompt the user in Shiny (not the R console) so they can correct their
analysis.

Corey
